# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: fix-encoding-pragma
        args: [--remove]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.9.16
          - flake8-pyi==23.10.0

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
      - id: markdownlint
        name: markdownlint-fix
        alias: markdownlint-fix
        args: ["--fix"]
        stages: [manual]

  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
    - id: mypy

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
      - id: poetry-check
        stages: [push]
      - id: poetry-lock
        stages: [push]
      #- id: poetry-export
      #  args: ["-f", "requirements.txt", "-o", "requirements.txt"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: tox
        language: system
        pass_filenames: false
        types: [python]
        args:
          [
            "-e pylint"
          ]

  - repo: https://github.com/crate-ci/typos
    rev: 'v1.16.25'
    hooks:
      - id: typos
        exclude: "(_typos.toml|.gitignore)"
