# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: fix-encoding-pragma
        args: [--remove]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      #- id: poetry-export
      #  args: ["-f", "requirements.txt", "-o", "requirements.txt"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: tox
        language: system
        types: [python]
        args:
          [
            "-e pylint"
          ]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
      - id: markdownlint
        name: markdownlint-fix
        alias: markdownlint-fix
        args: ["--fix"]
        stages: [manual]

  - repo: https://github.com/crate-ci/typos
    rev: v1.13.6
    hooks:
      - id: typos
        exclude: "(_typos.toml|.gitignore)"
