# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]
        os: [ubuntu-latest]
        include:
          - python-version: 3.6
            tox-env: py36
          - python-version: 3.7
            tox-env: py37
          - python-version: 3.8
            tox-env: py38
          - python-version: 3.9
            tox-env: py39
          - python-version: 3.10
            tox-env: py310
          - python-version: 3.11
            tox-env: py310
    env:
      TOXENV: ${{ matrix.tox-env }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Run tox
        run: |
          python -m tox --discover $(which python)
          python -m tox -e  pytest
        shell: bash
